id: I9CCD917D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:30:45+00:00'
last_modified: '2022-06-07T12:12:34.085158+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6897
  title: བོད་ཀྱི་སྔ་རབས་ཁྲིམས་སྲོལ་ཡིག་ཆ་བདམས་བསྒྲིགས／
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0EC6:
      image_group_id: I3CN6899
      title: Volume 1 of lha bla ma ye shes 'od kyi rnam thar/
      total_pages: 326
      order: 1
      base_file: 0EC6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
